Traceback (most recent call last):
  File "<input>", line 2, in <module>
Exception: this is the error message
